apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-node-cpu
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: high-node-cpu.rules
    rules:
    - alert: HighNodeCPUUsage
      expr: |
        (
          100 -
          (
            avg by(instance)(
              rate(node_cpu_seconds_total{mode="idle"}[5m])
            ) * 100
          )
        ) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage"
        description: "CPU usage on {{ $labels.instance }} has been above 80% for more than 5 minutes."
        