apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: peakwell-backend
        image: hazem231/peakwell-backend:v90
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8090

        envFrom:
        - configMapRef:
            name: peakwell-config
        - secretRef:
            name: peakwell-secret

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"