apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: peakwell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: hazem231/peakwell-keycloak:1.2
          args: ["start-dev", "--import-realm"]
          envFrom:
            - configMapRef:
                name: peakwell-config
            - secretRef:
                name: peakwell-secrets
          ports:
            - containerPort: 8080
            - containerPort: 9000
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data/h2
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 20
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-pvc