apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-event
  labels:
    app: ai-event-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-event-app
  template:
    metadata:
      labels:
        app: ai-event-app
    spec:
      containers:
      - name: peakwell-ai-event
        image: hazem231/ai-event:v8
        ports:
        - containerPort: 8004
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
