apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: peakwell
spec:
  type: ClusterIP      # Internal cluster communication only
  selector:
    app: frontend-app        # MUST match your Deployment's template labels
  ports:
  - protocol: TCP
    port: 4200        # The port the Service listens on inside the cluster
    targetPort: 80     # The port your container is actually running on
