apiVersion: apps/v1
kind: Deployment
metadata:
  name: allergen-predictor
  labels:
    app: allergen-predictor-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: allergen-predictor-app
  template:
    metadata:
      labels:
        app: allergen-predictor-app
    spec:
      containers:
      - name: peakwell-allergen-predictor
        image: hazem231/allergen-predictor:v7
        ports:
        - containerPort: 8003
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
