apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-event
  labels:
    app: ai-event-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-event-app
  template:
    metadata:
      labels:
        app: ai-event-app
    spec:
      containers:
      - name: peakwell-ai-event
        image: hazem231/ai-event:v20
        ports:
        - containerPort: 8004

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8004
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health/live
            port: 8004
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3

        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"