apiVersion: apps/v1
kind: Deployment
metadata:
  name: allergen-predictor
  labels:
    app: allergen-predictor-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allergen-predictor-app
  template:
    metadata:
      labels:
        app: allergen-predictor-app
    spec:
      containers:
      - name: peakwell-allergen-predictor
        image: hazem231/allergen-predictor:v19
        ports:
        - containerPort: 8003

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health/live
            port: 8003
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3

        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"